version: '3.8'

services:

  postgres:
    image: postgres
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: master
       POSTGRES_DB: postgresql
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./_scripts/postgres:/docker-entrypoint-initdb.d
